---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu, tag: latest}

inputs:
- name: terraform-output
- name: platform-automation-test
outputs:
- name: opsman-output

run:
  path: platform-automation-test/create-opsman-config.sh
