resources:
- name: terraforming-aws
  type: git
  source:
    uri: https://github.com/pivotal-cf/terraforming-aws
- name: platform-automation-test
  type: git
  source:
    uri: https://github.com/pvtl-dnoguerol/platform-automation-test.git
- name: terraform-tfvars-s3
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    regexp: terraform-(.*).tfvars
- name: terraform-output-s3
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    regexp: terraform.(.*).out
- name: opsman-config-s3
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region_name: ((region))
    bucket: ((bucket))
    regexp: opsman-config-(.*).yml

jobs:
- name: pave-iaas-job
  plan:
  - get: platform-automation-test
    trigger: false
  - get: terraforming-aws
    trigger: false
  - get: terraform-tfvars-s3
    trigger: false
  - task: pave-iaas-task
    file: platform-automation-test/pave-iaas.yml
  - put: terraform-output-s3
    params:
      file: terraform-output/terraform.*.out
  - task: create-opsman-config
    file: platform-automation-test/create-opsman-config.yml
  - put: opsman-config-s3
    params:
      file: opsman-output/opsman-config-*.yml
   